import { createContext, useContext, useState, useEffect, useRef, type ReactNode } from "react";
import { trackLanguageChange } from "@/lib/analytics";

export type Language = "en" | "es" | "ur" | "hi" | "ar";

/** Languages that use right-to-left script */
export const RTL_LANGUAGES: Language[] = ["ur", "ar"];

interface LanguageContextValue {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
}

const STORAGE_KEY = "clarify_language";

const LanguageContext = createContext<LanguageContextValue | null>(null);

// ── Translations ────────────────────────────────────────────────────────────

const strings: Record<Language, Record<string, string>> = {
  en: {
    // Nav / global
    "nav.topics": "Topics",
    "nav.tools": "Tools",
    "nav.ask": "Ask",
    "nav.about": "About",
    "nav.preview.topics.label": "Browse the library",
    "nav.preview.topics.title": "Understand common health topics",
    "nav.preview.topics.desc": "Clear explanations of conditions, symptoms, tests, and questions to ask your doctor.",
    "nav.preview.tools.label": "Try a tool",
    "nav.preview.tools.title": "Make health information easier",
    "nav.preview.tools.desc": "Translate medical jargon, browse the glossary, find a doctor, or organize visit notes.",
    "pathway.label": "Treatment pathway",
    "pathway.title": "What treatment usually looks like",
    "pathway.s1": "Getting diagnosed",
    "pathway.s2": "First steps",
    "pathway.s3": "If more help is needed",
    "pathway.s4": "Long-term care",
    "pathway.note": "Every person is different. Your doctor will build a plan that fits you.",
    "home.ctaTopics": "Browse health topics",
    "topic.cta2.title": "Got a confusing lab report?",
    "topic.cta2.sub": "Paste it in and get a plain-language translation.",
    "topic.cta2.button": "Open jargon translator",
    "plus.badge": "Plus · $5/mo",
    "nav.preview.about.label": "Our purpose",
    "nav.preview.about.title": "Why Clarify Health exists",
    "nav.preview.about.desc": "Learn how we write, review, and present health information in plain language.",
    "footer.copyright": `© ${new Date().getFullYear()} Clarify Health`,

    // Homepage
    "home.hero.line1": "Your health,",
    "home.hero.line2": "finally",
    "home.hero.line3": "makes sense.",
    "home.hero.sub": "Clear, trustworthy explanations of common health conditions — written so anyone can understand.",
    "home.search.placeholder": "Search a condition or ask a question...",
    "home.search.button": "Search",
    "home.stat.topics": "Health topics explained",
    "home.stat.sections": "Sections of plain-language content",
    "home.stat.jargon": "Jargon-free",
    "home.stat1.value": "88%",
    "home.stat1.label": "of American adults lack the skills to navigate the healthcare system",
    "home.stat2.value": "9 in 10",
    "home.stat2.label": "people struggle to understand everyday health information",
    "home.stat3.value": "$238 Billion",
    "home.stat3.label": "lost annually in the US due to low health literacy",
    "home.stat.source": "Sources: National Assessment of Adult Literacy (NAAL) · CDC · American Journal of Health Behavior",
    "home.explore": "Explore Topics",
    "home.readMore": "Read more",
    "home.holistic.label": "Evidence-Based Wellness",
    "home.holistic.title": "Holistic & Natural Health",
    "home.holistic.sub": "What does the research actually say? Each topic cites only peer-reviewed sources — PubMed, NIH, Harvard Health, and Mayo Clinic.",
    "home.meta.title": "Clarify Health — Plain-English Guides to Diabetes, Blood Pressure & More",
    "home.meta.desc": "Clear, trustworthy health education written in plain English. Understand diabetes, blood pressure, cholesterol, and more — no jargon, no confusion.",

    // Topics index
    "topics.title": "Health Topics",
    "topics.sub": "Tap any topic to read a clear, jargon-free explanation.",
    "topics.meta.title": "Health Topics | Clarify Health",
    "topics.meta.desc": "Browse 10 common health conditions explained in plain English. Diabetes, blood pressure, cholesterol, asthma, anxiety, and more.",

    // Topic detail
    "topic.backToTopics": "Topics",
    "topic.doctorQuestions": "5 questions to ask your doctor",
    "topic.copy": "Copy these questions",
    "topic.copied": "Copied!",
    "topic.sourcesDisclaimer": "Clarify Health simplifies information from trusted medical sources. Always consult your doctor.",
    "topic.sourcesTitle": "Sources & Further Reading",
    "topic.disclaimer": "This information is for educational purposes only and is not a substitute for professional medical advice. Always consult your doctor or a qualified health provider.",
    "topic.stillHaveQuestions": "Still have questions?",
    "topic.cta.sub": "Type any health question and get a clear, jargon-free answer.",
    "topic.cta.button": "Ask a question",
    "topic.notFound": "Topic not found",
    "topic.backLink": "← Back to Topics",

    // Ask page
    "ask.heading.ask1": "Ask anything about",
    "ask.heading.ask2": "your health.",
    "ask.heading.diag1": "Understand your",
    "ask.heading.diag2": "diagnosis.",
    "ask.sub.ask": "Get a plain-English answer in seconds. No jargon, no judgment.",
    "ask.sub.diag": "Paste what your doctor told you. We'll explain it in plain English.",
    "ask.tab.ask": "Ask a Question",
    "ask.tab.diagnosis": "Understand My Diagnosis",
    "ask.placeholder.ask": "Type your health question here...",
    "ask.placeholder.diag": "Paste your diagnosis, lab results, or doctor's notes here...",
    "ask.submit.ask": "Get your answer",
    "ask.submit.diag": "Explain this to me",
    "ask.loading": "Finding a clear answer...",
    "ask.rateLimit": "You've reached the hourly limit. Come back soon.",
    "ask.recentQuestions": "Recent questions",
    "ask.meta.title": "Ask a Health Question | Clarify Health",
    "ask.meta.desc": "Type any health question and get a clear, plain-English answer in seconds. No jargon, no judgment — just trustworthy information.",
    "ask.example.cholesterol": "What does high cholesterol mean?",
    "ask.example.anxiety": "How is anxiety treated?",
    "ask.example.sleep": "How can I sleep better?",
    "ask.example.a1c": "My A1C is 7.2%",
    "ask.example.hypertension": "Doctor said I have Stage 1 hypertension",
    "ask.example.tsh": "Lab results show TSH of 6.5",

    // About
    "about.title": "About",
    "about.why": "Why this exists.",
    "about.how": "How it was shaped.",
    "about.who": "Who built it.",
    "about.important": "Important.",
    "about.p1": "This site started at home. My mom was diagnosed with cancer, and suddenly our family was sitting in doctor's offices hearing words we did not understand — scan results, treatment plans, side effects, choices we had never heard of.",
    "about.p2": "I watched her try to look things up online and come away more confused than before. The information was there, but it was written for people who already work in medicine. So I started rewriting it: one page at a time, in plain language, the way I would explain it to my own family.",
    "about.p3": "Then I asked other people to help. I talked with patients, caregivers, nurses, and people who had just been given a hard diagnosis. I asked them what they wished they had known, what they could not find, and what made a doctor visit feel less frightening.",
    "about.p4": "Their answers decided what we build. A jargon translator, because no one should have to guess what a word means. Plain-language articles, because a diagnosis should not need a dictionary. Questions to bring to your doctor, because the hardest part is often knowing what to ask. Nothing here is decoration — every feature came from someone telling us what they actually needed.",
    "about.p5": "The goal is simple: make understanding your health easy. Not impressive. Not clever. Easy.",
    "about.disclaimer": "Clarify Health is an educational resource, not a substitute for professional medical advice. Always consult your doctor or a qualified healthcare provider.",
    "about.meta.title": "About Clarify Health — Our Story and Mission",
    "about.meta.desc": "Clarify Health started after a mother's cancer diagnosis. Plain-language health information, shaped by patients, caregivers, and nurses.",

    // Holistic
    "holistic.scienceTitle": "What the Science Says",
    "holistic.breadcrumbHome": "Home",
    "holistic.breadcrumbHolistic": "Holistic Health",
    "holistic.disclaimer": "Disclaimer:",
    "holistic.keyTakeaways": "Key Takeaways",
    "holistic.copyTakeaways": "Copy key takeaways",
    "topic.explainedSuffix": "Explained Simply",

    // 404
    "404.title": "404",
    "404.message": "Oops! Page not found",
    "404.link": "Return to Home",

    // Floating button
    "fab.label": "Ask a question",

    // Auth
    "auth.login": "Log In",
    "auth.signup": "Sign Up",
    "auth.signOut": "Sign Out",
    "auth.loginSub": "Welcome back. Log in to access your notes.",
    "auth.signupSub": "Create an account to save your doctor visit notes.",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.checkEmail": "Check your email",
    "auth.checkEmailSub": "We sent you a confirmation link. Click it to activate your account.",
    "auth.continueWithGoogle": "Continue with Google",
    "auth.orEmail": "or continue with email",
    "auth.myNotes": "My Notes",
    "auth.settings": "Settings",
    "nav.myNotes": "My Notes",

    // Notes
    "notes.title": "My Doctor Visits",
    "notes.add": "Add visit",
    "notes.addVisit": "Add a Visit",
    "notes.doctorName": "Doctor name",
    "notes.date": "Date of visit",
    "notes.specialty": "Specialty",
    "notes.notesLabel": "Notes",
    "notes.notesPlaceholder": "Write or paste your notes from the visit...",
    "notes.recording": "Upload recording",
    "notes.uploadAudio": "Upload audio (.mp3, .m4a, .wav, .webm)",
    "notes.save": "Save visit",
    "notes.process": "Process my notes",
    "notes.empty": "No visits yet. Add your first visit note.",
    "notes.yourNotes": "Your Notes",

    // Find a Doctor
    "nav.findDoctor": "Find a Doctor",
    "findDoctor.title": "Find the right doctor for you.",
    "findDoctor.sub": "Tell us what you're dealing with and we'll help you find the right specialist nearby.",
    "findDoctor.step1": "What are you dealing with?",
    "findDoctor.symptomsPlaceholder": "Describe your symptoms or condition in plain English...",
    "findDoctor.step2": "Where are you?",
    "findDoctor.zipPlaceholder": "Zip code",
    "findDoctor.useLocation": "Use my location",
    "findDoctor.preferences": "Preferences",
    "findDoctor.insurance": "Insurance type",
    "findDoctor.gender": "Gender preference",
    "findDoctor.language": "Language spoken",
    "findDoctor.acceptingNew": "Accepting new patients",
    "findDoctor.searchButton": "Find doctors →",
    "findDoctor.specialtyDetected": "Recommended specialty",
    "findDoctor.resultsFound": "doctors found",
    "findDoctor.noResults": "No doctors found for this area. Try a different zip code.",
    "findDoctor.whyThisDoctor": "Why this doctor",
    "findDoctor.viewProfile": "View profile",
    "findDoctor.disclaimer": "Doctor information sourced from the NPI National Provider Registry. Clarify Health does not endorse any provider. Always verify credentials independently.",
    "findDoctor.meta.title": "Find a Doctor | Clarify Health",
    "findDoctor.meta.desc": "Describe your symptoms in plain English and find the right specialist near you. AI-powered doctor matching from Clarify Health.",

    // Wellness Plan
    "nav.wellnessPlan": "My Wellness Plan",
    "wellness.title": "Your personalized wellness plan",
    "wellness.sub": "Answer a few questions and we'll create a plan that fits your life, your beliefs, and your health goals.",
    "wellness.yourPreferences": "Your Preferences",
    "wellness.aboutYou": "About you",
    "wellness.ageRange": "Age range",
    "wellness.healthGoals": "Health goals",
    "wellness.conditions": "Any diagnosed conditions (optional)",
    "wellness.conditionsPlaceholder": "e.g. diabetes, hypertension — optional",
    "wellness.dietTitle": "Diet preferences",
    "wellness.exerciseTitle": "Exercise",
    "wellness.activityLevel": "Current activity level",
    "wellness.limitations": "Physical limitations (optional)",
    "wellness.limitationsPlaceholder": "e.g. bad knees, limited mobility",
    "wellness.beliefsTitle": "Beliefs & preferences",
    "wellness.beliefsNote": "These preferences help us tailor suggestions. We never promote unproven treatments.",
    "wellness.generate": "Generate my plan →",
    "wellness.yourPlan": "Your Wellness Plan",
    "wellness.regenerate": "Regenerate",
    "wellness.sources": "Sources",
    "wellness.section.nutrition": "Nutrition recommendations",
    "wellness.section.exercise": "Exercise plan",
    "wellness.section.stressSleep": "Stress & sleep",
    "wellness.section.supplements": "Supplements",
    "wellness.section.mindfulness": "Spiritual & mindfulness",
    "wellness.disclaimer": "This wellness plan is for educational purposes only and is not medical advice. Always consult your doctor before making changes to your health routine.",
    "wellness.meta.title": "My Wellness Plan | Clarify Health",
    "wellness.meta.desc": "Get a personalized, evidence-based wellness plan tailored to your goals, diet, and beliefs.",

    // Home
    "home.hero": "Health information, in plain English.",
    "home.sub": "Skip the jargon. Get clear answers to common health questions, grounded in trusted sources.",
    "home.cta": "Ask a health question",
    "home.card1.h": "Explained simply",
    "home.card1.p": "Plain-English explainers for common conditions and tests.",
    "home.card2.h": "Grounded in sources",
    "home.card2.p": "Built from established, trustworthy health information.",
    "home.card3.h": "Built for questions",
    "home.card3.p": "Ask anything — get a clear answer in seconds.",
    "home.how": "How it works",
    "home.step1": "Type a question or browse our library of conditions.",
    "home.step2": "Read a short, plain-English explainer grounded in trusted sources.",
    "home.step3": "Bring the right questions to your next appointment.",
    "home.exampleLabel": "Example",
    "home.exampleTitle": "What is type 2 diabetes, really?",
    "home.exampleSub": "A short, plain-English explainer of what's happening in your body, what the numbers mean, and what to ask your doctor.",
    "home.exampleRead": "Read the article",
    "home.finalH": "Get a clear answer.",
    "home.finalNote": "Free. No account needed.",
    "home.introLabel": "Introducing",
    "home.introTitle": "Understand your health. Without the medical degree.",
    "home.introSub": "Clear answers for everyday people.",
    "home.trustTitle": "Health information should help you move forward.",
    "home.nextStep": "A clearer next step",
    "home.nextStepText": "Read it. Understand it. Bring better questions to your doctor.",
  },
  es: {
    // Nav / global
    "nav.topics": "Temas",
    "nav.tools": "Herramientas",
    "nav.ask": "Preguntar",
    "nav.about": "Acerca de",
    "nav.preview.topics.label": "Explora la biblioteca",
    "nav.preview.topics.title": "Entiende temas de salud comunes",
    "nav.preview.topics.desc": "Explicaciones claras de condiciones, síntomas, pruebas y preguntas para tu doctor.",
    "nav.preview.tools.label": "Prueba una herramienta",
    "nav.preview.tools.title": "Simplifica la información de salud",
    "nav.preview.tools.desc": "Traduce jerga médica, consulta el glosario, busca un doctor u organiza notas de visitas.",
    "pathway.label": "Ruta de tratamiento",
    "pathway.title": "Cómo suele ser el tratamiento",
    "pathway.s1": "El diagnóstico",
    "pathway.s2": "Primeros pasos",
    "pathway.s3": "Si se necesita más ayuda",
    "pathway.s4": "Cuidado a largo plazo",
    "pathway.note": "Cada persona es diferente. Tu doctor hará un plan para ti.",
    "home.ctaTopics": "Ver temas de salud",
    "topic.cta2.title": "¿Un informe de laboratorio confuso?",
    "topic.cta2.sub": "Pégalo y recibe una traducción en lenguaje sencillo.",
    "topic.cta2.button": "Abrir traductor de jerga",
    "plus.badge": "Plus · $5/mes",
    "nav.preview.about.label": "Nuestro propósito",
    "nav.preview.about.title": "Por qué existe Clarify Health",
    "nav.preview.about.desc": "Descubre cómo escribimos, revisamos y presentamos información de salud en lenguaje sencillo.",
    "footer.copyright": `© ${new Date().getFullYear()} Clarify Health`,

    // Homepage
    "home.hero.line1": "Tu salud,",
    "home.hero.line2": "por fin",
    "home.hero.line3": "tiene sentido.",
    "home.hero.sub": "Explicaciones claras y confiables de condiciones de salud comunes — escritas para que cualquiera las entienda.",
    "home.search.placeholder": "Busca una condición o haz una pregunta...",
    "home.search.button": "Buscar",
    "home.stat.topics": "Temas de salud explicados",
    "home.stat.sections": "Secciones en lenguaje sencillo",
    "home.stat.jargon": "Sin jerga médica",
    "home.stat1.value": "88%",
    "home.stat1.label": "de los adultos estadounidenses carecen de habilidades para navegar el sistema de salud",
    "home.stat2.value": "9 de 10",
    "home.stat2.label": "personas tienen dificultades para comprender la información de salud cotidiana",
    "home.stat3.value": "$238 Mil Millones",
    "home.stat3.label": "se pierden anualmente en EE.UU. debido a la baja alfabetización en salud",
    "home.stat.source": "Fuentes: National Assessment of Adult Literacy (NAAL) · CDC · American Journal of Health Behavior",
    "home.explore": "Explorar temas",
    "home.readMore": "Leer más",
    "home.holistic.label": "Bienestar basado en evidencia",
    "home.holistic.title": "Salud holística y natural",
    "home.holistic.sub": "¿Qué dice realmente la investigación? Cada tema cita solo fuentes revisadas por pares — PubMed, NIH, Harvard Health y Mayo Clinic.",
    "home.meta.title": "Clarify Health \u2014 Gu\u00edas de Salud en Espa\u00f1ol Sencillo",
    "home.meta.desc": "Educación de salud clara y confiable escrita en español sencillo. Entiende la diabetes, presión arterial, colesterol y más — sin jerga ni confusión.",

    // Topics index
    "topics.title": "Temas de salud",
    "topics.sub": "Toca cualquier tema para leer una explicación clara y sin jerga.",
    "topics.meta.title": "Temas de salud | Clarify Health",
    "topics.meta.desc": "Explora 10 condiciones de salud comunes explicadas en español sencillo. Diabetes, presión arterial, colesterol, asma, ansiedad y más.",

    // Topic detail
    "topic.backToTopics": "Temas",
    "topic.doctorQuestions": "5 preguntas para tu doctor",
    "topic.copy": "Copiar estas preguntas",
    "topic.copied": "¡Copiado!",
    "topic.sourcesDisclaimer": "Clarify Health simplifica información de fuentes médicas confiables. Siempre consulta a tu doctor.",
    "topic.sourcesTitle": "Fuentes y lecturas adicionales",
    "topic.disclaimer": "Esta información es solo con fines educativos y no sustituye el consejo médico profesional. Siempre consulta a tu doctor o a un profesional de salud.",
    "topic.stillHaveQuestions": "¿Aún tienes preguntas?",
    "topic.cta.sub": "Escribe cualquier pregunta de salud y recibe una respuesta clara y sin jerga.",
    "topic.cta.button": "Haz una pregunta",
    "topic.notFound": "Tema no encontrado",
    "topic.backLink": "← Volver a Temas",

    // Ask page
    "ask.heading.ask1": "Pregunta lo que quieras",
    "ask.heading.ask2": "sobre tu salud.",
    "ask.heading.diag1": "Entiende tu",
    "ask.heading.diag2": "diagnóstico.",
    "ask.sub.ask": "Recibe una respuesta en español sencillo en segundos. Sin jerga, sin juicios.",
    "ask.sub.diag": "Pega lo que tu doctor te dijo. Te lo explicamos en español sencillo.",
    "ask.tab.ask": "Haz una pregunta",
    "ask.tab.diagnosis": "Entiende tu diagnóstico",
    "ask.placeholder.ask": "Escribe tu pregunta de salud aquí...",
    "ask.placeholder.diag": "Pega tu diagnóstico, resultados de laboratorio o notas del doctor aquí...",
    "ask.submit.ask": "Obtener respuesta",
    "ask.submit.diag": "Explícame esto",
    "ask.loading": "Buscando una respuesta clara...",
    "ask.rateLimit": "Has alcanzado el límite por hora. Vuelve pronto.",
    "ask.recentQuestions": "Preguntas recientes",
    "ask.meta.title": "Haz una pregunta de salud | Clarify Health",
    "ask.meta.desc": "Escribe cualquier pregunta de salud y recibe una respuesta clara en español sencillo. Sin jerga, sin juicios — solo información confiable.",
    "ask.example.cholesterol": "¿Qué significa colesterol alto?",
    "ask.example.anxiety": "¿Cómo se trata la ansiedad?",
    "ask.example.sleep": "¿Cómo puedo dormir mejor?",
    "ask.example.a1c": "Mi A1C es 7.2%",
    "ask.example.hypertension": "El doctor dijo que tengo hipertensión etapa 1",
    "ask.example.tsh": "Mis resultados muestran TSH de 6.5",

    // About
    "about.title": "Acerca de",
    "about.why": "Por qué existe esto.",
    "about.how": "Cómo se fue formando.",
    "about.who": "Quién lo creó.",
    "about.important": "Importante.",
    "about.p1": "Este sitio empezó en casa. A mi mamá le diagnosticaron cáncer y de pronto nuestra familia estaba en los consultorios escuchando palabras que no entendíamos: resultados de estudios, planes de tratamiento, efectos secundarios, opciones que nunca habíamos oído.",
    "about.p2": "La vi intentar buscar información en internet y quedar más confundida que antes. La información estaba ahí, pero estaba escrita para personas que ya trabajan en la medicina. Así que empecé a reescribirla: una página a la vez, en lenguaje sencillo, como se la explicaría a mi propia familia.",
    "about.p3": "Después pedí ayuda a otras personas. Hablé con pacientes, con quienes los cuidan, con enfermeras y con personas que acababan de recibir un diagnóstico difícil. Les pregunté qué les hubiera gustado saber, qué no pudieron encontrar y qué hacía que una visita al médico fuera menos aterradora.",
    "about.p4": "Sus respuestas decidieron lo que construimos. Un traductor de términos médicos, porque nadie debería adivinar qué significa una palabra. Artículos en lenguaje claro, porque un diagnóstico no debería necesitar un diccionario. Preguntas para llevar al médico, porque lo más difícil suele ser saber qué preguntar. Nada aquí es adorno: cada función salió de alguien que nos dijo lo que realmente necesitaba.",
    "about.p5": "La meta es simple: que entender tu salud sea fácil. No impresionante. No complicado. Fácil.",
    "about.disclaimer": "Clarify Health es un recurso educativo, no un sustituto del consejo médico profesional. Siempre consulta a tu doctor o a un profesional de salud.",
    "about.meta.title": "Acerca de Clarify Health — Nuestra historia y misión",
    "about.meta.desc": "Clarify Health nació después del diagnóstico de cáncer de una madre. Información de salud en lenguaje sencillo, creada con pacientes, cuidadores y enfermeras.",

    // Holistic
    "holistic.scienceTitle": "Lo que dice la ciencia",
    "holistic.breadcrumbHome": "Inicio",
    "holistic.breadcrumbHolistic": "Salud holística",
    "holistic.disclaimer": "Aviso:",
    "holistic.keyTakeaways": "Puntos clave",
    "holistic.copyTakeaways": "Copiar puntos clave",
    "topic.explainedSuffix": "Explicado",

    // 404
    "404.title": "404",
    "404.message": "¡Ups! Página no encontrada",
    "404.link": "Volver al inicio",

    // Floating button
    "fab.label": "Haz una pregunta",

    // Auth
    "auth.login": "Iniciar sesión",
    "auth.signup": "Registrarse",
    "auth.signOut": "Cerrar sesión",
    "auth.loginSub": "Bienvenido de nuevo. Inicia sesión para acceder a tus notas.",
    "auth.signupSub": "Crea una cuenta para guardar tus notas de visitas médicas.",
    "auth.noAccount": "¿No tienes cuenta?",
    "auth.hasAccount": "¿Ya tienes cuenta?",
    "auth.checkEmail": "Revisa tu correo",
    "auth.checkEmailSub": "Te enviamos un enlace de confirmación. Haz clic para activar tu cuenta.",
    "auth.continueWithGoogle": "Continuar con Google",
    "auth.orEmail": "o continúa con tu correo",
    "auth.myNotes": "Mis notas",
    "auth.settings": "Configuración",
    "nav.myNotes": "Mis notas",
    "notes.title": "Mis visitas médicas",
    "notes.add": "Agregar visita",
    "notes.addVisit": "Agregar una visita",
    "notes.doctorName": "Nombre del doctor",
    "notes.date": "Fecha de la visita",
    "notes.specialty": "Especialidad",
    "notes.notesLabel": "Notas",
    "notes.notesPlaceholder": "Escribe o pega tus notas de la visita...",
    "notes.recording": "Subir grabación",
    "notes.uploadAudio": "Subir audio (.mp3, .m4a, .wav, .webm)",
    "notes.save": "Guardar visita",
    "notes.process": "Procesar mis notas",
    "notes.empty": "Aún no hay visitas. Agrega tu primera nota de visita.",
    "notes.yourNotes": "Tus notas",

    "nav.findDoctor": "Buscar doctor",
    "findDoctor.title": "Encuentra el doctor adecuado para ti.",
    "findDoctor.sub": "Dinos qué te pasa y te ayudaremos a encontrar al especialista correcto cerca de ti.",
    "findDoctor.step1": "¿Qué te pasa?",
    "findDoctor.symptomsPlaceholder": "Describe tus síntomas o condición en palabras simples...",
    "findDoctor.step2": "¿Dónde estás?",
    "findDoctor.zipPlaceholder": "Código postal",
    "findDoctor.useLocation": "Usar mi ubicación",
    "findDoctor.preferences": "Preferencias",
    "findDoctor.insurance": "Tipo de seguro",
    "findDoctor.gender": "Preferencia de género",
    "findDoctor.language": "Idioma",
    "findDoctor.acceptingNew": "Acepta nuevos pacientes",
    "findDoctor.searchButton": "Buscar doctores →",
    "findDoctor.specialtyDetected": "Especialidad recomendada",
    "findDoctor.resultsFound": "doctores encontrados",
    "findDoctor.noResults": "No se encontraron doctores en esta área. Intenta con otro código postal.",
    "findDoctor.whyThisDoctor": "Por qué este doctor",
    "findDoctor.viewProfile": "Ver perfil",
    "findDoctor.disclaimer": "Información de doctores del Registro Nacional de Proveedores NPI. Clarify Health no respalda a ningún proveedor.",
    "findDoctor.meta.title": "Buscar un Doctor | Clarify Health",
    "findDoctor.meta.desc": "Describe tus síntomas y encuentra al especialista adecuado cerca de ti.",

    "nav.wellnessPlan": "Mi plan de bienestar",
    "wellness.title": "Tu plan de bienestar personalizado",
    "wellness.sub": "Responde algunas preguntas y crearemos un plan que se adapte a tu vida, tus creencias y tus metas de salud.",
    "wellness.yourPreferences": "Tus preferencias",
    "wellness.aboutYou": "Sobre ti",
    "wellness.ageRange": "Rango de edad",
    "wellness.healthGoals": "Metas de salud",
    "wellness.conditions": "Condiciones diagnosticadas (opcional)",
    "wellness.conditionsPlaceholder": "ej. diabetes, hipertensión — opcional",
    "wellness.dietTitle": "Preferencias de dieta",
    "wellness.exerciseTitle": "Ejercicio",
    "wellness.activityLevel": "Nivel de actividad actual",
    "wellness.limitations": "Limitaciones físicas (opcional)",
    "wellness.limitationsPlaceholder": "ej. rodillas malas, movilidad limitada",
    "wellness.beliefsTitle": "Creencias y preferencias",
    "wellness.beliefsNote": "Estas preferencias nos ayudan a personalizar las sugerencias. Nunca promovemos tratamientos no probados.",
    "wellness.generate": "Generar mi plan →",
    "wellness.yourPlan": "Tu plan de bienestar",
    "wellness.regenerate": "Regenerar",
    "wellness.sources": "Fuentes",
    "wellness.section.nutrition": "Recomendaciones de nutrición",
    "wellness.section.exercise": "Plan de ejercicio",
    "wellness.section.stressSleep": "Estrés y sueño",
    "wellness.section.supplements": "Suplementos",
    "wellness.section.mindfulness": "Espiritualidad y meditación",
    "wellness.disclaimer": "Este plan es solo para fines educativos y no es consejo médico. Siempre consulta a tu doctor.",
    "wellness.meta.title": "Mi Plan de Bienestar | Clarify Health",
    "wellness.meta.desc": "Obtén un plan de bienestar personalizado basado en evidencia.",

    // Home
    "home.hero": "Información de salud, en lenguaje sencillo.",
    "home.sub": "Olvídate de la jerga. Respuestas claras basadas en fuentes confiables.",
    "home.cta": "Haz una pregunta de salud",
    "home.card1.h": "Explicado con sencillez",
    "home.card1.p": "Explicaciones en lenguaje sencillo de condiciones y pruebas comunes.",
    "home.card2.h": "Basado en fuentes",
    "home.card2.p": "Creado a partir de información de salud confiable.",
    "home.card3.h": "Hecho para preguntas",
    "home.card3.p": "Pregunta lo que sea — obtén una respuesta clara en segundos.",
    "home.how": "Cómo funciona",
    "home.step1": "Escribe una pregunta o explora nuestra biblioteca de condiciones.",
    "home.step2": "Lee una explicación breve y sencilla basada en fuentes confiables.",
    "home.step3": "Lleva las preguntas correctas a tu próxima cita.",
    "home.exampleLabel": "Ejemplo",
    "home.exampleTitle": "¿Qué es realmente la diabetes tipo 2?",
    "home.exampleSub": "Una explicación breve y sencilla de lo que ocurre en tu cuerpo, qué significan los números y qué preguntar a tu doctor.",
    "home.exampleRead": "Lee el artículo",
    "home.finalH": "Obtén una respuesta clara.",
    "home.finalNote": "Gratis. No necesitas cuenta.",
    "home.introLabel": "Presentamos",
    "home.introTitle": "Entiende tu salud. Sin un título médico.",
    "home.introSub": "Respuestas claras para todos.",
    "home.trustTitle": "La información de salud debe ayudarte a avanzar.",
    "home.nextStep": "Un próximo paso más claro",
    "home.nextStepText": "Léelo. Entiéndelo. Lleva mejores preguntas a tu doctor.",
  },
  ur: {
    // Nav / global
    "nav.topics": "موضوعات",
    "nav.tools": "ٹولز",
    "nav.ask": "پوچھیں",
    "nav.about": "ہمارے بارے میں",
    "nav.preview.topics.label": "لائبریری دیکھیں",
    "nav.preview.topics.title": "عام صحت کے موضوعات سمجھیں",
    "nav.preview.topics.desc": "بیماریوں، علامات، ٹیسٹوں اور ڈاکٹر سے پوچھنے کے سوالات کی آسان وضاحت۔",
    "nav.preview.tools.label": "ٹول آزمائیں",
    "nav.preview.tools.title": "صحت کی معلومات آسان بنائیں",
    "nav.preview.tools.desc": "طبی اصطلاحات سمجھیں، لغت دیکھیں، ڈاکٹر تلاش کریں یا ملاقات کے نوٹس ترتیب دیں۔",
    "pathway.label": "علاج کا راستہ",
    "pathway.title": "علاج عام طور پر کیسا ہوتا ہے",
    "pathway.s1": "تشخیص",
    "pathway.s2": "پہلے اقدامات",
    "pathway.s3": "اگر مزید مدد درکار ہو",
    "pathway.s4": "طویل مدتی دیکھ بھال",
    "pathway.note": "ہر شخص مختلف ہے۔ آپ کا ڈاکٹر آپ کے لیے منصوبہ بنائے گا۔",
    "home.ctaTopics": "صحت کے موضوعات دیکھیں",
    "topic.cta2.title": "لیب رپورٹ سمجھ نہیں آ رہی؟",
    "topic.cta2.sub": "اسے پیسٹ کریں اور آسان زبان میں ترجمہ حاصل کریں۔",
    "topic.cta2.button": "اصطلاح مترجم کھولیں",
    "plus.badge": "Plus · $5/ماہ",
    "nav.preview.about.label": "ہمارا مقصد",
    "nav.preview.about.title": "Clarify Health کیوں موجود ہے",
    "nav.preview.about.desc": "جانیں کہ ہم صحت کی معلومات کو آسان زبان میں کیسے لکھتے اور پیش کرتے ہیں۔",
    "footer.copyright": `© ${new Date().getFullYear()} Clarify Health`,

    // Homepage
    "home.hero.line1": "آپ کی صحت،",
    "home.hero.line2": "آخرکار",
    "home.hero.line3": "سمجھ آئے۔",
    "home.hero.sub": "عام صحت کے مسائل کی واضح اور قابل اعتماد وضاحتیں — جو کوئی بھی سمجھ سکے۔",
    "home.search.placeholder": "کوئی بیماری تلاش کریں یا سوال پوچھیں...",
    "home.search.button": "تلاش کریں",
    "home.stat.topics": "صحت کے موضوعات کی وضاحت",
    "home.stat.sections": "آسان زبان میں حصے",
    "home.stat.jargon": "طبی اصطلاحات سے پاک",
    "home.stat1.value": "88%",
    "home.stat1.label": "امریکی بالغوں میں صحت کے نظام کو سمجھنے کی صلاحیت کی کمی ہے",
    "home.stat2.value": "10 میں 9",
    "home.stat2.label": "لوگوں کو روزمرہ صحت کی معلومات سمجھنے میں مشکل ہوتی ہے",
    "home.stat3.value": "$238 ارب",
    "home.stat3.label": "صحت کی ناخواندگی کی وجہ سے امریکہ میں سالانہ نقصان",
    "home.stat.source": "ذرائع: National Assessment of Adult Literacy (NAAL) · CDC · American Journal of Health Behavior",
    "home.explore": "موضوعات دیکھیں",
    "home.readMore": "مزید پڑھیں",
    "home.holistic.label": "شواہد پر مبنی تندرستی",
    "home.holistic.title": "مکمل اور قدرتی صحت",
    "home.holistic.sub": "تحقیق اصل میں کیا کہتی ہے؟ ہر موضوع صرف تسلیم شدہ ذرائع کا حوالہ دیتا ہے — PubMed، NIH، Harvard Health، اور Mayo Clinic۔",
    "home.meta.title": "Clarify Health — آپ کی صحت، آسان زبان میں",
    "home.meta.desc": "واضح، قابل اعتماد صحت کی تعلیم آسان اردو میں۔ ذیابیطس، بلڈ پریشر، کولیسٹرول اور بہت کچھ سمجھیں — بغیر الجھن کے۔",

    // Topics index
    "topics.title": "صحت کے موضوعات",
    "topics.sub": "کسی بھی موضوع کو دبائیں اور آسان وضاحت پڑھیں۔",
    "topics.meta.title": "صحت کے موضوعات | Clarify Health",
    "topics.meta.desc": "آسان اردو میں 10 عام صحت کے مسائل کی وضاحت۔ ذیابیطس، بلڈ پریشر، کولیسٹرول، دمہ، اضطراب اور مزید۔",

    // Topic detail
    "topic.backToTopics": "موضوعات",
    "topic.doctorQuestions": "اپنے ڈاکٹر سے پوچھنے کے 5 سوالات",
    "topic.copy": "سوالات کاپی کریں",
    "topic.copied": "کاپی ہو گیا!",
    "topic.sourcesDisclaimer": "Clarify Health قابل اعتماد طبی ذرائع سے معلومات کو آسان بناتا ہے۔ ہمیشہ اپنے ڈاکٹر سے مشورہ کریں۔",
    "topic.sourcesTitle": "ذرائع اور مزید پڑھائی",
    "topic.disclaimer": "یہ معلومات صرف تعلیمی مقاصد کے لیے ہیں اور پیشہ ورانہ طبی مشورے کا متبادل نہیں ہیں۔ ہمیشہ اپنے ڈاکٹر سے مشورہ کریں۔",
    "topic.stillHaveQuestions": "ابھی بھی سوالات ہیں؟",
    "topic.cta.sub": "کوئی بھی صحت کا سوال لکھیں اور واضح جواب حاصل کریں۔",
    "topic.cta.button": "سوال پوچھیں",
    "topic.notFound": "موضوع نہیں ملا",
    "topic.backLink": "← موضوعات پر واپس",

    // Ask page
    "ask.heading.ask1": "اپنی صحت کے بارے میں",
    "ask.heading.ask2": "کچھ بھی پوچھیں۔",
    "ask.heading.diag1": "اپنی تشخیص",
    "ask.heading.diag2": "سمجھیں۔",
    "ask.sub.ask": "سیکنڈوں میں آسان زبان میں جواب حاصل کریں۔ بغیر اصطلاحات، بغیر فیصلے کے۔",
    "ask.sub.diag": "اپنے ڈاکٹر نے جو بتایا وہ لکھیں۔ ہم آسان زبان میں سمجھائیں گے۔",
    "ask.tab.ask": "سوال پوچھیں",
    "ask.tab.diagnosis": "تشخیص سمجھیں",
    "ask.placeholder.ask": "اپنا صحت کا سوال یہاں لکھیں...",
    "ask.placeholder.diag": "اپنی تشخیص، لیب رزلٹ، یا ڈاکٹر کی ہدایات یہاں لکھیں...",
    "ask.submit.ask": "جواب حاصل کریں",
    "ask.submit.diag": "مجھے سمجھائیں",
    "ask.loading": "واضح جواب تلاش ہو رہا ہے...",
    "ask.rateLimit": "آپ نے فی گھنٹہ حد پوری کر لی ہے۔ جلد واپس آئیں۔",
    "ask.recentQuestions": "حالیہ سوالات",
    "ask.meta.title": "صحت کا سوال پوچھیں | Clarify Health",
    "ask.meta.desc": "کوئی بھی صحت کا سوال لکھیں اور سیکنڈوں میں آسان جواب حاصل کریں۔ بغیر اصطلاحات، بغیر فیصلے کے۔",
    "ask.example.cholesterol": "ہائی کولیسٹرول کا کیا مطلب ہے؟",
    "ask.example.anxiety": "اضطراب کا علاج کیسے ہوتا ہے؟",
    "ask.example.sleep": "میں بہتر نیند کیسے لے سکتا ہوں؟",
    "ask.example.a1c": "میرا A1C 7.2% ہے",
    "ask.example.hypertension": "ڈاکٹر نے کہا مجھے ہائی بلڈ پریشر ہے",
    "ask.example.tsh": "لیب رزلٹ میں TSH 6.5 ہے",

    // About
    "about.title": "ہمارے بارے میں",
    "about.why": "یہ کیوں موجود ہے۔",
    "about.how": "اسے کیسے بنایا گیا۔",
    "about.who": "کس نے بنایا۔",
    "about.important": "ضروری۔",
    "about.p1": "یہ سائٹ گھر سے شروع ہوئی۔ میری امّی کو کینسر کا پتہ چلا، اور اچانک ہمارا خاندان ڈاکٹر کے دفتر میں ایسے الفاظ سن رہا تھا جنہیں ہم نہیں سمجھتے — ٹیسٹ کی رپورٹ، علاج کے طریقے، ان کے اثرات، اور ایسے انتخاب جو ہم نے پہلے کبھی نہیں سنے تھے۔",
    "about.p2": "میں نے دیکھا کہ وہ آن لائن معلومات ڈھونڈنے کی کوشش کرتی ہیں اور پہلے سے زیادہ پریشان ہو کر واپس آتی ہیں۔ معلومات موجود تھیں، لیکن وہ ان لوگوں کے لیے لکھی گئی تھیں جو پہلے سے طب کے شعبے میں کام کرتے ہیں۔ تو میں نے انہیں دوبارہ لکھنا شروع کیا — ایک صفحہ ایک وقت میں، آسان زبان میں، جیسے میں اپنے ہی خاندان کو سمجھاتا ہوں۔",
    "about.p3": "پھر میں نے دوسروں سے مدد مانگی۔ میں نے مریضوں، ان کا خیال رکھنے والوں، نرسوں، اور ان لوگوں سے بات کی جنہیں ابھی مشکل تشخیص ملی تھی۔ میں نے پوچھا کہ انہیں کیا جاننا چاہیے تھا، کیا چیز وہ نہ ڈھونڈ سکیں، اور کس چیز سے ڈاکٹر سے ملنا کم ڈراونا ہوتا ہے۔",
    "about.p4": "ان کے جوابوں نے طے کیا کہ ہم کیا بناتے ہیں۔ ایک طبی الفاظ کا ترجمہ کرنے والا، کیونکہ کسی کو یہ اندازہ نہیں لگانا چاہیے کہ کسی لفظ کا کیا مطلب ہے۔ آسان زبان میں مضامین، کیونکہ تشخیص کے لیے ڈکشنری نہیں چاہیے۔ ڈاکٹر سے پوچھنے کے سوالات، کیونکہ سب سے مشکل یہ ہوتا ہے کہ کیا پوچھنا ہے۔ یہاں کوئی چیز سجاول کے لیے نہیں — ہر فیچر اس بات سے آیا کہ کسی نے ہمیں بتایا کہ اسے واقعی کیا چاہیے تھا۔",
    "about.p5": "مقصد سادہ ہے: اپنی صحت کو سمجھنا آسان ہو۔ نہ پُرجوش، نہ پیچیدہ۔ آسان۔",
    "about.disclaimer": "Clarify Health ایک تعلیمی وسیلہ ہے، پیشہ ورانہ طبی مشورے کا متبادل نہیں۔ ہمیشہ اپنے ڈاکٹر سے مشورہ کریں۔",
    "about.meta.title": "Clarify Health کے بارے میں — ہماری کہانی اور مشن",
    "about.meta.desc": "Clarify Health امّی کے کینسر کا پتہ چلنے کے بعد شروع ہوا۔ آسان زبان میں صحت کی معلومات، مریضوں، خیال رکھنے والوں اور نرسوں کے تجربات سے بنی۔",

    // 404
    "404.title": "404",
    "404.message": "اوہو! صفحہ نہیں ملا",
    "404.link": "ہوم پیج پر واپس جائیں",

    // Holistic
    "holistic.scienceTitle": "سائنس کیا کہتی ہے",
    "holistic.breadcrumbHome": "ہوم",
    "holistic.breadcrumbHolistic": "مکمل صحت",
    "holistic.disclaimer": "اعلان:",
    "holistic.keyTakeaways": "اہم نکات",
    "holistic.copyTakeaways": "اہم نکات کاپی کریں",
    "topic.explainedSuffix": "آسان وضاحت",

    // Floating button
    "fab.label": "سوال پوچھیں",
    "auth.login": "لاگ ان",
    "auth.signup": "سائن اپ",
    "auth.signOut": "سائن آؤٹ",
    "auth.loginSub": "خوش آمدید۔ اپنے نوٹس تک رسائی کے لیے لاگ ان کریں۔",
    "auth.signupSub": "اپنے ڈاکٹر کے دوروں کے نوٹس محفوظ کرنے کے لیے اکاؤنٹ بنائیں۔",
    "auth.noAccount": "اکاؤنٹ نہیں ہے؟",
    "auth.hasAccount": "پہلے سے اکاؤنٹ ہے؟",
    "auth.checkEmail": "اپنا ای میل چیک کریں",
    "auth.checkEmailSub": "ہم نے آپ کو ایک تصدیقی لنک بھیجا ہے۔",
    "auth.continueWithGoogle": "گوگل کے ساتھ جاری رکھیں",
    "auth.orEmail": "یا ای میل کے ساتھ جاری رکھیں",
    "auth.myNotes": "میرے نوٹس",
    "auth.settings": "ترتیبات",
    "nav.myNotes": "میرے نوٹس",
    "notes.title": "میرے ڈاکٹر کے دورے",
    "notes.add": "دورہ شامل کریں",
    "notes.addVisit": "دورہ شامل کریں",
    "notes.doctorName": "ڈاکٹر کا نام",
    "notes.date": "دورے کی تاریخ",
    "notes.specialty": "تخصص",
    "notes.notesLabel": "نوٹس",
    "notes.notesPlaceholder": "اپنے دورے کے نوٹس لکھیں یا پیسٹ کریں...",
    "notes.recording": "ریکارڈنگ اپ لوڈ کریں",
    "notes.uploadAudio": "آڈیو اپ لوڈ کریں",
    "notes.save": "دورہ محفوظ کریں",
    "notes.process": "میرے نوٹس پروسیس کریں",
    "notes.empty": "ابھی تک کوئی دورے نہیں۔ اپنا پہلا نوٹ شامل کریں۔",
    "notes.yourNotes": "آپ کے نوٹس",

    "nav.findDoctor": "ڈاکٹر تلاش کریں",
    "findDoctor.title": "اپنے لیے صحیح ڈاکٹر تلاش کریں۔",
    "findDoctor.sub": "ہمیں بتائیں کہ آپ کو کیا مسئلہ ہے اور ہم آپ کو قریبی ماہر تلاش کرنے میں مدد کریں گے۔",
    "findDoctor.step1": "آپ کو کیا مسئلہ ہے؟",
    "findDoctor.symptomsPlaceholder": "اپنی علامات یا حالت سادہ الفاظ میں بیان کریں...",
    "findDoctor.step2": "آپ کہاں ہیں؟",
    "findDoctor.zipPlaceholder": "زپ کوڈ",
    "findDoctor.useLocation": "میرا مقام استعمال کریں",
    "findDoctor.preferences": "ترجیحات",
    "findDoctor.insurance": "انشورنس کی قسم",
    "findDoctor.gender": "صنف کی ترجیح",
    "findDoctor.language": "زبان",
    "findDoctor.acceptingNew": "نئے مریض قبول کرتا ہے",
    "findDoctor.searchButton": "ڈاکٹر تلاش کریں →",
    "findDoctor.specialtyDetected": "تجویز کردہ تخصص",
    "findDoctor.resultsFound": "ڈاکٹر ملے",
    "findDoctor.noResults": "اس علاقے میں کوئی ڈاکٹر نہیں ملا۔ مختلف زپ کوڈ آزمائیں۔",
    "findDoctor.whyThisDoctor": "یہ ڈاکٹر کیوں",
    "findDoctor.viewProfile": "پروفائل دیکھیں",
    "findDoctor.disclaimer": "ڈاکٹروں کی معلومات NPI نیشنل پرووائیڈر رجسٹری سے حاصل کی گئی ہیں۔",
    "findDoctor.meta.title": "ڈاکٹر تلاش کریں | Clarify Health",
    "findDoctor.meta.desc": "اپنی علامات بیان کریں اور اپنے قریب صحیح ماہر تلاش کریں۔",

    "nav.wellnessPlan": "میرا فلاحی منصوبہ",
    "wellness.title": "آپ کا ذاتی فلاحی منصوبہ",
    "wellness.sub": "چند سوالات کے جوابات دیں اور ہم آپ کی زندگی، عقائد اور صحت کے اہداف کے مطابق منصوبہ بنائیں گے۔",
    "wellness.yourPreferences": "آپ کی ترجیحات",
    "wellness.aboutYou": "آپ کے بارے میں",
    "wellness.ageRange": "عمر کی حد",
    "wellness.healthGoals": "صحت کے اہداف",
    "wellness.conditions": "تشخیص شدہ حالات (اختیاری)",
    "wellness.conditionsPlaceholder": "مثلاً ذیابیطس، ہائی بلڈ پریشر",
    "wellness.dietTitle": "غذائی ترجیحات",
    "wellness.exerciseTitle": "ورزش",
    "wellness.activityLevel": "موجودہ سرگرمی کی سطح",
    "wellness.limitations": "جسمانی حدود (اختیاری)",
    "wellness.limitationsPlaceholder": "مثلاً گھٹنوں کا درد",
    "wellness.beliefsTitle": "عقائد اور ترجیحات",
    "wellness.beliefsNote": "یہ ترجیحات ہمیں تجاویز کو اپنی مرضی کے مطابق بنانے میں مدد کرتی ہیں۔",
    "wellness.generate": "میرا منصوبہ بنائیں →",
    "wellness.yourPlan": "آپ کا فلاحی منصوبہ",
    "wellness.regenerate": "دوبارہ بنائیں",
    "wellness.sources": "ذرائع",
    "wellness.section.nutrition": "غذائی سفارشات",
    "wellness.section.exercise": "ورزش کا منصوبہ",
    "wellness.section.stressSleep": "تناؤ اور نیند",
    "wellness.section.supplements": "سپلیمنٹس",
    "wellness.section.mindfulness": "روحانیت اور مراقبہ",
    "wellness.disclaimer": "یہ منصوبہ صرف تعلیمی مقاصد کے لیے ہے۔ ہمیشہ اپنے ڈاکٹر سے مشورہ کریں۔",
    "wellness.meta.title": "میرا فلاحی منصوبہ | Clarify Health",
    "wellness.meta.desc": "اپنے اہداف اور ترجیحات کے مطابق ذاتی فلاحی منصوبہ حاصل کریں۔",

    // Home
    "home.hero": "صحت کی معلومات، آسان زبان میں۔",
    "home.sub": "مشکل اصطلاحات سے بچیں۔ معتبر ذرائع پر مبنی واضح جوابات حاصل کریں۔",
    "home.cta": "صحت کا سوال پوچھیں",
    "home.card1.h": "آسانی سے سمجھایا گیا",
    "home.card1.p": "عام بیماریوں اور ٹیسٹوں کی سادہ وضاحت۔",
    "home.card2.h": "معتبر ذرائع پر مبنی",
    "home.card2.p": "قابل اعتماد صحت کی معلومات سے تیار کردہ۔",
    "home.card3.h": "سوالات کے لیے بنایا گیا",
    "home.card3.p": "کچھ بھی پوچھیں — سیکنڈوں میں واضح جواب پائیں۔",
    "home.how": "یہ کیسے کام کرتا ہے",
    "home.step1": "سوال لکھیں یا ہماری بیماریوں کی لائبریری دیکھیں۔",
    "home.step2": "معتبر ذرائع پر مبنی ایک مختصر اور آسان وضاحت پڑھیں۔",
    "home.step3": "اپنی اگلی ملاقات میں صحیح سوالات لے کر جائیں۔",
    "home.exampleLabel": "مثال",
    "home.exampleTitle": "ٹائپ 2 ذیابیطس اصل میں کیا ہے؟",
    "home.exampleSub": "آپ کے جسم میں کیا ہو رہا ہے، نمبروں کا کیا مطلب ہے، اور ڈاکٹر سے کیا پوچھنا ہے — اس کی مختصر، آسان وضاحت۔",
    "home.exampleRead": "مضمون پڑھیں",
    "home.finalH": "ایک واضح جواب حاصل کریں۔",
    "home.finalNote": "مفت۔ اکاؤنٹ کی ضرورت نہیں۔",
    "home.introLabel": "تعارف",
    "home.introTitle": "اپنی صحت کو سمجھیں۔ طبی ڈگری کے بغیر۔",
    "home.introSub": "ہر شخص کے لیے واضح جوابات۔",
    "home.trustTitle": "صحت کی معلومات آپ کو آگے بڑھنے میں مدد دینی چاہئیں۔",
    "home.nextStep": "ایک واضح اگلا قدم",
    "home.nextStepText": "پڑھیں۔ سمجھیں۔ اپنے ڈاکٹر سے بہتر سوالات پوچھیں۔",
  },
  hi: {
    // Nav / global
    "nav.topics": "विषय",
    "nav.tools": "टूल्स",
    "nav.ask": "पूछें",
    "nav.about": "हमारे बारे में",
    "nav.preview.topics.label": "लाइब्रेरी देखें",
    "nav.preview.topics.title": "आम स्वास्थ्य विषय समझें",
    "nav.preview.topics.desc": "स्थितियों, लक्षणों, जांचों और डॉक्टर से पूछने वाले सवालों की सरल व्याख्या।",
    "nav.preview.tools.label": "कोई टूल आज़माएं",
    "nav.preview.tools.title": "स्वास्थ्य जानकारी सरल बनाएं",
    "nav.preview.tools.desc": "मेडिकल शब्द समझें, शब्दकोश देखें, डॉक्टर खोजें या विज़िट नोट्स व्यवस्थित करें।",
    "pathway.label": "इलाज का रास्ता",
    "pathway.title": "इलाज आमतौर पर कैसा होता है",
    "pathway.s1": "निदान",
    "pathway.s2": "पहले कदम",
    "pathway.s3": "अगर और मदद चाहिए",
    "pathway.s4": "लंबे समय की देखभाल",
    "pathway.note": "हर व्यक्ति अलग है। आपका डॉक्टर आपके लिए योजना बनाएगा।",
    "home.ctaTopics": "स्वास्थ्य विषय देखें",
    "topic.cta2.title": "लैब रिपोर्ट समझ नहीं आ रही?",
    "topic.cta2.sub": "इसे पेस्ट करें और आसान भाषा में अनुवाद पाएं।",
    "topic.cta2.button": "शब्द अनुवादक खोलें",
    "plus.badge": "Plus · $5/माह",
    "nav.preview.about.label": "हमारा उद्देश्य",
    "nav.preview.about.title": "Clarify Health क्यों है",
    "nav.preview.about.desc": "जानें कि हम स्वास्थ्य जानकारी को सरल भाषा में कैसे लिखते और प्रस्तुत करते हैं।",
    "footer.copyright": `© ${new Date().getFullYear()} Clarify Health`,

    // Homepage
    "home.hero.line1": "आपकी सेहत,",
    "home.hero.line2": "आखिरकार",
    "home.hero.line3": "समझ आए।",
    "home.hero.sub": "आम स्वास्थ्य स्थितियों की स्पष्ट और विश्वसनीय व्याख्याएं — जो कोई भी समझ सके।",
    "home.search.placeholder": "कोई बीमारी खोजें या सवाल पूछें...",
    "home.search.button": "खोजें",
    "home.stat.topics": "स्वास्थ्य विषयों की व्याख्या",
    "home.stat.sections": "सरल भाषा में अनुभाग",
    "home.stat.jargon": "चिकित्सा शब्दावली से मुक्त",
    "home.stat1.value": "88%",
    "home.stat1.label": "अमेरिकी वयस्कों में स्वास्थ्य प्रणाली को समझने की क्षमता की कमी है",
    "home.stat2.value": "10 में 9",
    "home.stat2.label": "लोगों को रोजमर्रा की स्वास्थ्य जानकारी समझने में कठिनाई होती है",
    "home.stat3.value": "$238 अरब",
    "home.stat3.label": "कम स्वास्थ्य साक्षरता के कारण अमेरिका में सालाना नुकसान",
    "home.stat.source": "स्रोत: National Assessment of Adult Literacy (NAAL) · CDC · American Journal of Health Behavior",
    "home.explore": "विषय देखें",
    "home.readMore": "और पढ़ें",
    "home.holistic.label": "प्रमाण-आधारित कल्याण",
    "home.holistic.title": "समग्र और प्राकृतिक स्वास्थ्य",
    "home.holistic.sub": "शोध वास्तव में क्या कहता है? हर विषय केवल सहकर्मी-समीक्षित स्रोतों का हवाला देता है — PubMed, NIH, Harvard Health, और Mayo Clinic।",
    "home.meta.title": "Clarify Health — आपकी सेहत, सरल हिंदी में",
    "home.meta.desc": "स्पष्ट, विश्वसनीय स्वास्थ्य शिक्षा सरल हिंदी में। मधुमेह, रक्तचाप, कोलेस्ट्रॉल और बहुत कुछ समझें — बिना उलझन के।",

    // Topics index
    "topics.title": "स्वास्थ्य विषय",
    "topics.sub": "किसी भी विषय को दबाएं और सरल व्याख्या पढ़ें।",
    "topics.meta.title": "स्वास्थ्य विषय | Clarify Health",
    "topics.meta.desc": "सरल हिंदी में 10 आम स्वास्थ्य स्थितियों की व्याख्या। मधुमेह, रक्तचाप, कोलेस्ट्रॉल, अस्थमा, चिंता और बहुत कुछ।",

    // Topic detail
    "topic.backToTopics": "विषय",
    "topic.doctorQuestions": "अपने डॉक्टर से पूछने के 5 सवाल",
    "topic.copy": "सवाल कॉपी करें",
    "topic.copied": "कॉपी हो गया!",
    "topic.sourcesDisclaimer": "Clarify Health विश्वसनीय चिकित्सा स्रोतों से जानकारी को सरल बनाता है। हमेशा अपने डॉक्टर से सलाह लें।",
    "topic.sourcesTitle": "स्रोत और अतिरिक्त पठन",
    "topic.disclaimer": "यह जानकारी केवल शैक्षिक उद्देश्यों के लिए है और पेशेवर चिकित्सा सलाह का विकल्प नहीं है। हमेशा अपने डॉक्टर से सलाह लें।",
    "topic.stillHaveQuestions": "अभी भी सवाल हैं?",
    "topic.cta.sub": "कोई भी स्वास्थ्य सवाल लिखें और स्पष्ट जवाब पाएं।",
    "topic.cta.button": "सवाल पूछें",
    "topic.notFound": "विषय नहीं मिला",
    "topic.backLink": "← विषयों पर वापस",

    // Ask page
    "ask.heading.ask1": "अपनी सेहत के बारे में",
    "ask.heading.ask2": "कुछ भी पूछें।",
    "ask.heading.diag1": "अपनी जांच रिपोर्ट",
    "ask.heading.diag2": "समझें।",
    "ask.sub.ask": "सेकंडों में सरल भाषा में जवाब पाएं। बिना शब्दावली, बिना आलोचना के।",
    "ask.sub.diag": "आपके डॉक्टर ने जो बताया वह लिखें। हम सरल भाषा में समझाएंगे।",
    "ask.tab.ask": "सवाल पूछें",
    "ask.tab.diagnosis": "जांच रिपोर्ट समझें",
    "ask.placeholder.ask": "अपना स्वास्थ्य सवाल यहां लिखें...",
    "ask.placeholder.diag": "अपनी जांच रिपोर्ट, लैब रिजल्ट, या डॉक्टर के नोट्स यहां लिखें...",
    "ask.submit.ask": "जवाब पाएं",
    "ask.submit.diag": "मुझे समझाएं",
    "ask.loading": "स्पष्ट जवाब खोज रहे हैं...",
    "ask.rateLimit": "आपने प्रति घंटा सीमा पूरी कर ली है। जल्द वापस आएं।",
    "ask.recentQuestions": "हाल के सवाल",
    "ask.meta.title": "स्वास्थ्य सवाल पूछें | Clarify Health",
    "ask.meta.desc": "कोई भी स्वास्थ्य सवाल लिखें और सेकंडों में सरल जवाब पाएं। बिना शब्दावली, बिना आलोचना — सिर्फ विश्वसनीय जानकारी।",
    "ask.example.cholesterol": "हाई कोलेस्ट्रॉल का क्या मतलब है?",
    "ask.example.anxiety": "चिंता का इलाज कैसे होता है?",
    "ask.example.sleep": "मैं बेहतर नींद कैसे ले सकता हूं?",
    "ask.example.a1c": "मेरा A1C 7.2% है",
    "ask.example.hypertension": "डॉक्टर ने कहा मुझे हाई ब्लड प्रेशर है",
    "ask.example.tsh": "लैब रिजल्ट में TSH 6.5 है",

    // About
    "about.title": "हमारे बारे में",
    "about.why": "यह क्यों है।",
    "about.how": "इसे कैसे बनाया गया।",
    "about.who": "किसने बनाया।",
    "about.important": "ज़रूरी।",
    "about.p1": "यह साइट घर से शुरू हुई। मेरी अम्मा को कैंसर पता चला, और अचानक हमारा परिवार डॉक्टर के दफ़्तर में ऐसे शब्द सुन रहा था जिन्हें हम नहीं समझते — जाँच की रिपोर्ट, इलाज के तरीके, उनके असर, और ऐसे विकल्प जो हमने पहले कभी नहीं सुने थे।",
    "about.p2": "मैंने देखा कि वह ऑनलाइन जानकारी ढूँढने की कोशिश करती हैं और पहले से ज़्यादा उलझन में लौटती हैं। जानकारी मौजूद थी, पर वह उन लोगों के लिए लिखी गई थी जो पहले से चिकित्सा के काम में हैं। तो मैंने उसे दोबारा लिखना शुरू किया — एक-एक पेज, आसान भाषा में, जैसे मैं अपने ही परिवार को समझाता हूँ।",
    "about.p3": "फिर मैंने दूसरों से मदद माँगी। मैंने मरीज़ों, उनका ख़्याल रखने वालों, नर्सों, और जिनको हाल में कठिन निदान मिला है उनसे बात की। मैंने पूछा कि उन्हें क्या पता होना चाहिए था, वे क्या नहीं ढूँढ पाईं, और किस चीज़ से डॉक्टर से मिलना कम डरावना होता है।",
    "about.p4": "उनके जवाबों ने तय किया कि हम क्या बनाते हैं। एक मेडिकल शब्दों का अनुवादक, क्योंकि किसी को अंदाज़ा नहीं लगाना चाहिए कि किसी शब्द का क्या मतलब है। आसान भाषा में लेख, क्योंकि निदान के लिए शब्दकोश नहीं चाहिए। डॉक्टर से पूछने के सवाल, क्योंकि सबसे कठिन होता है यह जानना कि क्या पूछना है। यहाँ कोई चीज़ सजावट के लिए नहीं — हर फ़ीचर इस बात से आया कि किसी ने हमें बताया कि उसे सच में क्या चाहिए था।",
    "about.p5": "मक़सद सीधा है: अपनी सेहत को समझना आसान हो। न दिखावटी, न उलझा हुआ। आसान।",
    "about.disclaimer": "Clarify Health एक शैक्षिक संसाधन है, पेशेवर चिकित्सा सलाह का विकल्प नहीं। हमेशा अपने डॉक्टर से सलाह लें।",
    "about.meta.title": "Clarify Health के बारे में — हमारी कहानी और मिसन",
    "about.meta.desc": "Clarify Health अम्मा के कैंसर पता चलने के बाद शुरू हुआ। आसान भाषा में सेहत की जानकारी, मरीज़ों, ख़्याल रखने वालों और नर्सों के तजुربों से बनī।",

    // 404
    "404.title": "404",
    "404.message": "ओह! पेज नहीं मिला",
    "404.link": "होम पेज पर वापस जाएं",

    // Floating button
    "fab.label": "सवाल पूछें",
    "auth.login": "लॉग इन",
    "auth.signup": "साइन अप",
    "auth.signOut": "साइन आउट",
    "auth.loginSub": "वापस स्वागत है। अपने नोट्स तक पहुँचने के लिए लॉग इन करें।",
    "auth.signupSub": "अपने डॉक्टर विज़िट नोट्स सेव करने के लिए अकाउंट बनाएं।",
    "auth.noAccount": "अकाउंट नहीं है?",
    "auth.hasAccount": "पहले से अकाउंट है?",
    "auth.checkEmail": "अपना ईमेल जांचें",
    "auth.checkEmailSub": "हमने आपको एक पुष्टिकरण लिंक भेजा है।",
    "auth.continueWithGoogle": "Google के साथ जारी रखें",
    "auth.orEmail": "या ईमेल से जारी रखें",
    "auth.myNotes": "मेरे नोट्स",
    "auth.settings": "सेटिंग्स",
    "nav.myNotes": "मेरे नोट्स",
    "notes.title": "मेरे डॉक्टर विज़िट",
    "notes.add": "विज़िट जोड़ें",
    "notes.addVisit": "विज़िट जोड़ें",
    "notes.doctorName": "डॉक्टर का नाम",
    "notes.date": "विज़िट की तारीख",
    "notes.specialty": "विशेषता",
    "notes.notesLabel": "नोट्स",
    "notes.notesPlaceholder": "अपने विज़िट के नोट्स लिखें या पेस्ट करें...",
    "notes.recording": "रिकॉर्डिंग अपलोड करें",
    "notes.uploadAudio": "ऑडियो अपलोड करें",
    "notes.save": "विज़िट सेव करें",
    "notes.process": "मेरे नोट्स प्रोसेस करें",
    "notes.empty": "अभी तक कोई विज़िट नहीं। अपना पहला नोट जोड़ें।",
    "notes.yourNotes": "आपके नोट्स",

    "nav.findDoctor": "डॉक्टर खोजें",
    "findDoctor.title": "अपने लिए सही डॉक्टर खोजें।",
    "findDoctor.sub": "हमें बताएं कि आपको क्या समस्या है और हम आपके पास सही विशेषज्ञ खोजने में मदद करेंगे।",
    "findDoctor.step1": "आपको क्या समस्या है?",
    "findDoctor.symptomsPlaceholder": "अपने लक्षण या स्थिति सरल भाषा में बताएं...",
    "findDoctor.step2": "आप कहाँ हैं?",
    "findDoctor.zipPlaceholder": "ज़िप कोड",
    "findDoctor.useLocation": "मेरा स्थान उपयोग करें",
    "findDoctor.preferences": "प्राथमिकताएं",
    "findDoctor.insurance": "बीमा प्रकार",
    "findDoctor.gender": "लिंग प्राथमिकता",
    "findDoctor.language": "भाषा",
    "findDoctor.acceptingNew": "नए मरीज स्वीकार करता है",
    "findDoctor.searchButton": "डॉक्टर खोजें →",
    "findDoctor.specialtyDetected": "अनुशंसित विशेषता",
    "findDoctor.resultsFound": "डॉक्टर मिले",
    "findDoctor.noResults": "इस क्षेत्र में कोई डॉक्टर नहीं मिला। दूसरा ज़िप कोड आज़माएं।",
    "findDoctor.whyThisDoctor": "यह डॉक्टर क्यों",
    "findDoctor.viewProfile": "प्रोफ़ाइल देखें",
    "findDoctor.disclaimer": "डॉक्टर की जानकारी NPI नेशनल प्रोवाइडर रजिस्ट्री से प्राप्त।",
    "findDoctor.meta.title": "डॉक्टर खोजें | Clarify Health",
    "findDoctor.meta.desc": "अपने लक्षण बताएं और अपने पास सही विशेषज्ञ खोजें।",

    "nav.wellnessPlan": "मेरी वेलनेस योजना",
    "wellness.title": "आपकी व्यक्तिगत वेलनेस योजना",
    "wellness.sub": "कुछ सवालों के जवाब दें और हम आपके जीवन, विश्वासों और स्वास्थ्य लक्ष्यों के अनुसार योजना बनाएंगे।",
    "wellness.yourPreferences": "आपकी प्राथमिकताएं",
    "wellness.aboutYou": "आपके बारे में",
    "wellness.ageRange": "आयु सीमा",
    "wellness.healthGoals": "स्वास्थ्य लक्ष्य",
    "wellness.conditions": "निदान की गई स्थितियां (वैकल्पिक)",
    "wellness.conditionsPlaceholder": "जैसे मधुमेह, उच्च रक्तचाप",
    "wellness.dietTitle": "आहार प्राथमिकताएं",
    "wellness.exerciseTitle": "व्यायाम",
    "wellness.activityLevel": "वर्तमान गतिविधि स्तर",
    "wellness.limitations": "शारीरिक सीमाएं (वैकल्पिक)",
    "wellness.limitationsPlaceholder": "जैसे घुटनों में दर्द",
    "wellness.beliefsTitle": "विश्वास और प्राथमिकताएं",
    "wellness.beliefsNote": "ये प्राथमिकताएं हमें सुझावों को अनुकूलित करने में मदद करती हैं।",
    "wellness.generate": "मेरी योजना बनाएं →",
    "wellness.yourPlan": "आपकी वेलनेस योजना",
    "wellness.regenerate": "फिर से बनाएं",
    "wellness.sources": "स्रोत",
    "wellness.section.nutrition": "पोषण सिफारिशें",
    "wellness.section.exercise": "व्यायाम योजना",
    "wellness.section.stressSleep": "तनाव और नींद",
    "wellness.section.supplements": "सप्लीमेंट्स",
    "wellness.section.mindfulness": "आध्यात्मिकता और ध्यान",
    "wellness.disclaimer": "यह योजना केवल शैक्षिक उद्देश्यों के लिए है। हमेशा अपने डॉक्टर से परामर्श करें।",
    "wellness.meta.title": "मेरी वेलनेस योजना | Clarify Health",
    "wellness.meta.desc": "अपने लक्ष्यों और प्राथमिकताओं के अनुसार व्यक्तिगत वेलनेस योजना प्राप्त करें।",

    // Home
    "home.hero": "स्वास्थ्य जानकारी, सरल भाषा में।",
    "home.sub": "तकनीकी शब्दों को छोड़ें। विश्वसनीय स्रोतों पर आधारित स्पष्ट उत्तर पाएं।",
    "home.cta": "एक स्वास्थ्य प्रश्न पूछें",
    "home.card1.h": "सरलता से समझाया गया",
    "home.card1.p": "सामान्य स्थितियों और जांचों की सरल भाषा में व्याख्या।",
    "home.card2.h": "विश्वसनीय स्रोतों पर आधारित",
    "home.card2.p": "स्थापित और भरोसेमंद स्वास्थ्य जानकारी से तैयार।",
    "home.card3.h": "प्रश्नों के लिए बनाया गया",
    "home.card3.p": "कुछ भी पूछें — सेकंडों में स्पष्ट उत्तर पाएं।",
    "home.how": "यह कैसे काम करता है",
    "home.step1": "एक प्रश्न लिखें या हमारी स्थितियों की लाइब्रेरी देखें।",
    "home.step2": "विश्वसनीय स्रोतों पर आधारित एक संक्षिप्त, सरल व्याख्या पढ़ें।",
    "home.step3": "अपनी अगली मुलाकात में सही प्रश्न लेकर जाएं।",
    "home.exampleLabel": "उदाहरण",
    "home.exampleTitle": "टाइप 2 मधुमेह वास्तव में क्या है?",
    "home.exampleSub": "आपके शरीर में क्या हो रहा है, संख्याओं का क्या अर्थ है, और डॉक्टर से क्या पूछना है — इसकी एक संक्षिप्त, सरल व्याख्या।",
    "home.exampleRead": "लेख पढ़ें",
    "home.finalH": "एक स्पष्ट उत्तर पाएं।",
    "home.finalNote": "मुफ्त। खाते की आवश्यकता नहीं।",
    "home.introLabel": "परिचय",
    "home.introTitle": "अपनी सेहत को समझें। मेडिकल डिग्री के बिना।",
    "home.introSub": "हर व्यक्ति के लिए स्पष्ट उत्तर।",
    "home.trustTitle": "स्वास्थ्य जानकारी आपको आगे बढ़ने में मदद करनी चाहिए।",
    "home.nextStep": "एक स्पष्ट अगला कदम",
    "home.nextStepText": "पढ़ें। समझें। अपने डॉक्टर से बेहतर सवाल पूछें।",
  },
  ar: {
    // Nav / global
    "nav.topics": "المواضيع",
    "nav.tools": "الأدوات",
    "nav.ask": "اسأل",
    "nav.about": "من نحن",
    "nav.preview.topics.label": "تصفح المكتبة",
    "nav.preview.topics.title": "افهم المواضيع الصحية الشائعة",
    "nav.preview.topics.desc": "شروحات واضحة للحالات والأعراض والفحوصات والأسئلة التي تطرحها على طبيبك.",
    "nav.preview.tools.label": "جرب أداة",
    "nav.preview.tools.title": "بسّط المعلومات الصحية",
    "nav.preview.tools.desc": "فسّر المصطلحات الطبية، وتصفح المسرد، وابحث عن طبيب، ونظّم ملاحظات الزيارة.",
    "pathway.label": "مسار العلاج",
    "pathway.title": "كيف يبدو العلاج عادةً",
    "pathway.s1": "التشخيص",
    "pathway.s2": "الخطوات الأولى",
    "pathway.s3": "إذا احتجت مساعدة أكثر",
    "pathway.s4": "الرعاية طويلة المدى",
    "pathway.note": "كل شخص مختلف. سيضع طبيبك خطة تناسبك.",
    "home.ctaTopics": "تصفح المواضيع الصحية",
    "topic.cta2.title": "تقرير مختبر مربك؟",
    "topic.cta2.sub": "الصقه واحصل على ترجمة بلغة بسيطة.",
    "topic.cta2.button": "افتح مترجم المصطلحات",
    "plus.badge": "Plus · $5/شهر",
    "nav.preview.about.label": "هدفنا",
    "nav.preview.about.title": "لماذا يوجد Clarify Health",
    "nav.preview.about.desc": "تعرّف على كيفية كتابة ومراجعة وتقديم المعلومات الصحية بلغة بسيطة.",
    "footer.copyright": `© ${new Date().getFullYear()} Clarify Health`,

    // Homepage
    "home.hero.line1": "صحتك،",
    "home.hero.line2": "أخيراً",
    "home.hero.line3": "أصبحت مفهومة.",
    "home.hero.sub": "شروحات واضحة وموثوقة للحالات الصحية الشائعة — مكتوبة ليفهمها الجميع.",
    "home.search.placeholder": "ابحث عن حالة صحية أو اطرح سؤالاً...",
    "home.search.button": "بحث",
    "home.stat.topics": "مواضيع صحية موضحة",
    "home.stat.sections": "أقسام بلغة بسيطة",
    "home.stat.jargon": "خالية من المصطلحات الطبية",
    "home.stat1.value": "88%",
    "home.stat1.label": "من البالغين الأمريكيين يفتقرون إلى المهارات اللازمة للتعامل مع النظام الصحي",
    "home.stat2.value": "9 من 10",
    "home.stat2.label": "أشخاص يواجهون صعوبة في فهم المعلومات الصحية اليومية",
    "home.stat3.value": "238 مليار دولار",
    "home.stat3.label": "تُفقد سنوياً في أمريكا بسبب ضعف الثقافة الصحية",
    "home.stat.source": "المصادر: National Assessment of Adult Literacy (NAAL) · CDC · American Journal of Health Behavior",
    "home.explore": "تصفح المواضيع",
    "home.readMore": "اقرأ المزيد",
    "home.holistic.label": "عافية مبنية على الأدلة",
    "home.holistic.title": "الصحة الشاملة والطبيعية",
    "home.holistic.sub": "ماذا يقول البحث فعلاً؟ كل موضوع يستشهد فقط بمصادر محكّمة — PubMed و NIH و Harvard Health و Mayo Clinic.",
    "home.meta.title": "Clarify Health — صحتك بلغة بسيطة",
    "home.meta.desc": "تعليم صحي واضح وموثوق بالعربية البسيطة. افهم السكري وضغط الدم والكوليسترول والمزيد — بدون تعقيد.",

    // Topics index
    "topics.title": "المواضيع الصحية",
    "topics.sub": "اضغط على أي موضوع لقراءة شرح واضح وبسيط.",
    "topics.meta.title": "المواضيع الصحية | Clarify Health",
    "topics.meta.desc": "تصفح 10 حالات صحية شائعة موضحة بالعربية البسيطة. السكري وضغط الدم والكوليسترول والربو والقلق والمزيد.",

    // Topic detail
    "topic.backToTopics": "المواضيع",
    "topic.doctorQuestions": "5 أسئلة لتسألها لطبيبك",
    "topic.copy": "انسخ هذه الأسئلة",
    "topic.copied": "تم النسخ!",
    "topic.sourcesDisclaimer": "Clarify Health يبسط المعلومات من مصادر طبية موثوقة. استشر طبيبك دائماً.",
    "topic.sourcesTitle": "المصادر والقراءات الإضافية",
    "topic.disclaimer": "هذه المعلومات لأغراض تعليمية فقط وليست بديلاً عن الاستشارة الطبية المتخصصة. استشر طبيبك دائماً.",
    "topic.stillHaveQuestions": "لا تزال لديك أسئلة؟",
    "topic.cta.sub": "اكتب أي سؤال صحي واحصل على إجابة واضحة وبسيطة.",
    "topic.cta.button": "اطرح سؤالاً",
    "topic.notFound": "الموضوع غير موجود",
    "topic.backLink": "← العودة إلى المواضيع",

    // Ask page
    "ask.heading.ask1": "اسأل أي شيء عن",
    "ask.heading.ask2": "صحتك.",
    "ask.heading.diag1": "افهم",
    "ask.heading.diag2": "تشخيصك.",
    "ask.sub.ask": "احصل على إجابة بلغة بسيطة في ثوانٍ. بدون مصطلحات، بدون أحكام.",
    "ask.sub.diag": "الصق ما أخبرك به طبيبك. سنشرحه لك بلغة بسيطة.",
    "ask.tab.ask": "اطرح سؤالاً",
    "ask.tab.diagnosis": "افهم تشخيصك",
    "ask.placeholder.ask": "اكتب سؤالك الصحي هنا...",
    "ask.placeholder.diag": "الصق تشخيصك أو نتائج الفحوصات أو ملاحظات الطبيب هنا...",
    "ask.submit.ask": "احصل على الإجابة",
    "ask.submit.diag": "اشرح لي هذا",
    "ask.loading": "جارٍ البحث عن إجابة واضحة...",
    "ask.rateLimit": "لقد وصلت إلى الحد الأقصى للساعة. عد قريباً.",
    "ask.recentQuestions": "الأسئلة الأخيرة",
    "ask.meta.title": "اطرح سؤالاً صحياً | Clarify Health",
    "ask.meta.desc": "اكتب أي سؤال صحي واحصل على إجابة واضحة بالعربية البسيطة في ثوانٍ. بدون مصطلحات، بدون أحكام — معلومات موثوقة فقط.",
    "ask.example.cholesterol": "ماذا يعني ارتفاع الكوليسترول؟",
    "ask.example.anxiety": "كيف يُعالج القلق؟",
    "ask.example.sleep": "كيف يمكنني النوم بشكل أفضل؟",
    "ask.example.a1c": "نتيجة A1C هي 7.2%",
    "ask.example.hypertension": "الطبيب قال عندي ضغط دم مرتفع المرحلة الأولى",
    "ask.example.tsh": "نتائج الفحص تُظهر TSH 6.5",

    // About
    "about.title": "من نحن",
    "about.why": "لماذا يوجد هذا.",
    "about.how": "كيف صُنع.",
    "about.who": "من بناه.",
    "about.important": "مهم.",
    "about.p1": "بدأ هذا الموقع من البيت. شُخِّصت والدتي بالسرطان، وفجأة كانت عائلتنا تجلس في عيادات الأطباء تسمع كلمات لا نفهمها: نتائج الفحوصات، خطط العلاج، الآثار الجانبية، وخيارات لم نسمع بها من قبل.",
    "about.p2": "رأيتها تحاول البحث عن المعلومات على الإنترنت وتعود أكثر ارتباكًا من قبل. كانت المعلومات موجودة، لكنها كُتبت لأشخاص يعملون أصلًا في الطب. فبدأت بإعادة كتابتها: صفحة واحدة في كل مرة، بلغة واضحة، كما أشرحها لعائلتي.",
    "about.p3": "ثم طلبت المساعدة من آخرين. تحدثت مع مرضى، ومن يعتنون بهم، وممرضين، وأشخاص تلقّوا للتو تشخيصًا صعبًا. سألتهم: ماذا كانوا يتمنون لو عرفوا؟ ما الذي لم يجدوه؟ وما الذي يجعل زيارة الطبيب أقل إخافة؟",
    "about.p4": "إجابتهم هي التي قرّرت ما نبنيه. مترجم للمصطلحات الطبية، لأن أحدًا لا ينبغي أن يخمّن معنى كلمة. مقالات بلغة بسيطة، لأن التشخيص لا يحتاج إلى قاموس. أسئلة تأخذها إلى الطبيب، لأن أصعب شيء غالبًا أن تعرف ماذا تسأل. لا شيء هنا للزينة — كل ميزة جاءت من شخص أخبرنا بما يحتاجه فعلًا.",
    "about.p5": "الهدف بسيط: أن تفهم صحتك بسهولة. ليس بشكل مبهر. ولا بشكل معقّد. بسهولة.",
    "about.disclaimer": "Clarify Health مصدر تعليمي وليس بديلاً عن الاستشارة الطبية المتخصصة. استشر طبيبك دائماً.",
    "about.meta.title": "عن Clarify Health — قصتنا ومهمتنا",
    "about.meta.desc": "بدأ Clarify Health بعد تشخيص والدتي بالسرطان. معلومات صحية بلغة بسيطة، صاغها مرضى ومَن يعتنون بهم وممرضون.",

    // 404
    "404.title": "404",
    "404.message": "عذراً! الصفحة غير موجودة",
    "404.link": "العودة إلى الصفحة الرئيسية",

    // Floating button
    "fab.label": "اطرح سؤالاً",
    "auth.login": "تسجيل الدخول",
    "auth.signup": "إنشاء حساب",
    "auth.signOut": "تسجيل الخروج",
    "auth.loginSub": "مرحبًا بعودتك. سجّل الدخول للوصول إلى ملاحظاتك.",
    "auth.signupSub": "أنشئ حسابًا لحفظ ملاحظات زياراتك الطبية.",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.hasAccount": "لديك حساب بالفعل؟",
    "auth.checkEmail": "تحقق من بريدك الإلكتروني",
    "auth.checkEmailSub": "أرسلنا لك رابط تأكيد.",
    "auth.continueWithGoogle": "المتابعة مع Google",
    "auth.orEmail": "أو تابع بالبريد الإلكتروني",
    "auth.myNotes": "ملاحظاتي",
    "auth.settings": "الإعدادات",
    "nav.myNotes": "ملاحظاتي",
    "notes.title": "زياراتي الطبية",
    "notes.add": "إضافة زيارة",
    "notes.addVisit": "إضافة زيارة",
    "notes.doctorName": "اسم الطبيب",
    "notes.date": "تاريخ الزيارة",
    "notes.specialty": "التخصص",
    "notes.notesLabel": "الملاحظات",
    "notes.notesPlaceholder": "اكتب أو الصق ملاحظات زيارتك...",
    "notes.recording": "رفع تسجيل",
    "notes.uploadAudio": "رفع ملف صوتي",
    "notes.save": "حفظ الزيارة",
    "notes.process": "معالجة ملاحظاتي",
    "notes.empty": "لا توجد زيارات بعد. أضف أول ملاحظة زيارة.",
    "notes.yourNotes": "ملاحظاتك",

    "nav.findDoctor": "ابحث عن طبيب",
    "findDoctor.title": "ابحث عن الطبيب المناسب لك.",
    "findDoctor.sub": "أخبرنا بما تعاني منه وسنساعدك في العثور على المتخصص المناسب بالقرب منك.",
    "findDoctor.step1": "ما الذي تعاني منه؟",
    "findDoctor.symptomsPlaceholder": "صِف أعراضك أو حالتك بلغة بسيطة...",
    "findDoctor.step2": "أين أنت؟",
    "findDoctor.zipPlaceholder": "الرمز البريدي",
    "findDoctor.useLocation": "استخدم موقعي",
    "findDoctor.preferences": "التفضيلات",
    "findDoctor.insurance": "نوع التأمين",
    "findDoctor.gender": "تفضيل الجنس",
    "findDoctor.language": "اللغة",
    "findDoctor.acceptingNew": "يقبل مرضى جدد",
    "findDoctor.searchButton": "ابحث عن أطباء →",
    "findDoctor.specialtyDetected": "التخصص الموصى به",
    "findDoctor.resultsFound": "أطباء وُجدوا",
    "findDoctor.noResults": "لم يتم العثور على أطباء في هذه المنطقة. جرّب رمزًا بريديًا مختلفًا.",
    "findDoctor.whyThisDoctor": "لماذا هذا الطبيب",
    "findDoctor.viewProfile": "عرض الملف الشخصي",
    "findDoctor.disclaimer": "معلومات الأطباء من سجل مقدمي الخدمات الوطني NPI.",
    "findDoctor.meta.title": "ابحث عن طبيب | Clarify Health",
    "findDoctor.meta.desc": "صِف أعراضك واعثر على المتخصص المناسب بالقرب منك.",

    "nav.wellnessPlan": "خطة العافية الخاصة بي",
    "wellness.title": "خطة العافية المخصصة لك",
    "wellness.sub": "أجب عن بعض الأسئلة وسننشئ خطة تناسب حياتك ومعتقداتك وأهدافك الصحية.",
    "wellness.yourPreferences": "تفضيلاتك",
    "wellness.aboutYou": "عنك",
    "wellness.ageRange": "الفئة العمرية",
    "wellness.healthGoals": "الأهداف الصحية",
    "wellness.conditions": "الحالات المشخصة (اختياري)",
    "wellness.conditionsPlaceholder": "مثل السكري، ارتفاع ضغط الدم",
    "wellness.dietTitle": "تفضيلات الغذاء",
    "wellness.exerciseTitle": "التمارين",
    "wellness.activityLevel": "مستوى النشاط الحالي",
    "wellness.limitations": "القيود الجسدية (اختياري)",
    "wellness.limitationsPlaceholder": "مثل آلام الركبة",
    "wellness.beliefsTitle": "المعتقدات والتفضيلات",
    "wellness.beliefsNote": "تساعدنا هذه التفضيلات في تخصيص الاقتراحات. لا نروّج أبدًا لعلاجات غير مثبتة.",
    "wellness.generate": "أنشئ خطتي →",
    "wellness.yourPlan": "خطة العافية الخاصة بك",
    "wellness.regenerate": "إعادة إنشاء",
    "wellness.sources": "المصادر",
    "wellness.section.nutrition": "توصيات التغذية",
    "wellness.section.exercise": "خطة التمارين",
    "wellness.section.stressSleep": "التوتر والنوم",
    "wellness.section.supplements": "المكملات",
    "wellness.section.mindfulness": "الروحانية والتأمل",
    "wellness.disclaimer": "هذه الخطة لأغراض تعليمية فقط وليست نصيحة طبية. استشر طبيبك دائمًا.",
    "wellness.meta.title": "خطة العافية | Clarify Health",
    "wellness.meta.desc": "احصل على خطة عافية مخصصة بناءً على أهدافك وتفضيلاتك.",

    // Home
    "home.hero": "معلومات صحية، بلغة بسيطة.",
    "home.sub": "تخطَّ المصطلحات الطبية. احصل على إجابات واضحة تستند إلى مصادر موثوقة.",
    "home.cta": "اطرح سؤالًا صحيًا",
    "home.card1.h": "موضح ببساطة",
    "home.card1.p": "شروحات بلغة بسيطة للحالات والفحوصات الشائعة.",
    "home.card2.h": "مبني على مصادر موثوقة",
    "home.card2.p": "مبني على معلومات صحية موثوقة ومعتمدة.",
    "home.card3.h": "مصمم للأسئلة",
    "home.card3.p": "اسأل أي شيء — احصل على إجابة واضحة في ثوانٍ.",
    "home.how": "كيف يعمل",
    "home.step1": "اكتب سؤالاً أو تصفّح مكتبتنا من الحالات.",
    "home.step2": "اقرأ شرحًا قصيرًا وبسيطًا يستند إلى مصادر موثوقة.",
    "home.step3": "خذ الأسئلة الصحيحة إلى موعدك القادم.",
    "home.exampleLabel": "مثال",
    "home.exampleTitle": "ما هو داء السكري من النوع 2 حقًا؟",
    "home.exampleSub": "شرح قصير وبسيط لما يحدث في جسمك، ومعنى الأرقام، وما الذي يجب سؤال طبيبك عنه.",
    "home.exampleRead": "اقرأ المقال",
    "home.finalH": "احصل على إجابة واضحة.",
    "home.finalNote": "مجاني. لا حاجة لحساب.",
    "home.introLabel": "نقدم لكم",
    "home.introTitle": "افهم صحتك. دون شهادة طبية.",
    "home.introSub": "إجابات واضحة للجميع.",
    "home.trustTitle": "يجب أن تساعدك المعلومات الصحية على التقدم.",
    "home.nextStep": "خطوة تالية أوضح",
    "home.nextStepText": "اقرأها. افهمها. واطرح أسئلة أفضل على طبيبك.",
  },
};

// ── Provider ────────────────────────────────────────────────────────────────

const VALID_LANGUAGES: Language[] = ["en", "es", "ur", "hi", "ar"];

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored && VALID_LANGUAGES.includes(stored as Language)) return stored as Language;
    } catch { /* noop */ }
    return "en";
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = RTL_LANGUAGES.includes(lang) ? "rtl" : "ltr";
    // Set lang-* class on body for font-family switching
    document.body.className = document.body.className.replace(/\blang-\w+\b/g, "");
    document.body.classList.add(`lang-${lang}`);
  }, [lang]);

  const isInitial = useRef(true);
  const setLang = (l: Language) => {
    setLangState(l);
    if (!isInitial.current) trackLanguageChange(l);
  };
  useEffect(() => { isInitial.current = false; }, []);

  const t = (key: string): string => strings[lang][key] ?? strings.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
